# ====================================================================================================
# ====================================================================================================
# ==================================Global Configurations=============================================
# ====================================================================================================
# ====================================================================================================
# The version of the image group in osm-seed, get it here: https://hub.docker.com/r/developmentseed/osmseed-web/tags/
osmSeedVersion: cloudProvider-b1fee6e
environment: development
# cloudProvider is provider where you are going to deploy osm-seed, it could be: aws, gcp, minikube
cloudProvider: minukube
# ====================================================================================================
# AWS: In case you are using the cloudProvider=aws set the below variables, We are assuming the nodes has a policies access to S3
# =================s===================================================================================
AWS_DEFAULT_REGION: us-east-1
AWS_S3_BUCKET: s3://osm-seed
AWS_ElasticBlockStore_volumeID : vol-1234bcd
AWS_ElasticBlockStore_size: 500Gi

# ====================================================================================================
# GCP: In case you are using the cloudProvider=gcp set the below variables
# ====================================================================================================
GCP_GCLOUD_PROJECT: osm-seed-12345
GCP_GCLOUD_SERVICE_KEY: xyz==
GCP_GS_OSM_PATH: gs://osm-seed
GCP_gcePersistentDisk_pdName: osm-seed-data-disk
GCP_gcePersistentDisk_size: 100Gi

# ====================================================================================================
# Ingress variables
# ====================================================================================================
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []

# ====================================================================================================
# Persist data configuration
# ====================================================================================================
persistence:
  enabled: false
  # accessMode: ReadWriteOnce
  # mountPath: /var/lib/postgresql/data
  # subPath: postgresql-db

# ====================================================================================================
# Domain app configuration
# ====================================================================================================
domain:
  #enabled, If you set  enabled=true, you should uncomment the following configurations
  enabled: false
  # domainName, Add here your domain or the fixed IP  where the server is running
  domainName: example.com
  protocolo: http

# ====================================================================================================
# ====================================================================================================
# ==================================Pods Configurations===============================================
# ====================================================================================================
# ====================================================================================================

# ====================================================================================================
# Variables for osm-seed database
# ====================================================================================================
db:
  enabled: true
  image: 'developmentseed/osmseed-db'
  env:
    POSTGRES_DB: openstreetmap
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: '1234'
  resources:
    enabled: false
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "1"

# ====================================================================================================
# Variables for osm-seed website
# ====================================================================================================
web:
  enabled: true
  image: 'developmentseed/osmseed-web'
  replicaCount: 1
  # Set staticIp, if you are using cloudProvider=gcp
  staticIp: 35.185.241.158
  env:
    MAILER_ADDRESS: smtp.gmail.com
    MAILER_DOMAIN: gmail.com
    MAILER_USERNAME: osmseed.test@gmail.com
    MAILER_PASSWORD: '12345678'
  resources:
    enabled: false
    requests:
      memory: "1Gi"
      cpu: "2"
    limits:
      memory: "2Gi"
      cpu: "2"

# ====================================================================================================
# Variables for osm-seed database backup and restore
# ====================================================================================================
dbbackup:
  enabled: true
  image: 'developmentseed/osmseed-backup-restore'
  schedule: '0 */1 * * *'
  env:
    DB_ACTION: backup
    CLEAN_BACKUPS: true
  resources:
    enabled: false
    requests:
      memory: "300Mi"
      cpu: "0.5"
    limits:
      memory: "400Mi"
      cpu: "0.6"

# ====================================================================================================
# Variables for osm-seed for osmosis, this configuration os to get the planet dump files from apidb
# ====================================================================================================
planetDump:
  enabled: true
  image: 'developmentseed/osmseed-planet-dump'
  schedule: '0 */1 * * *'
  env:
    CLEAN_BACKUPS: true
  resources:
    enabled: false
    requests:
      memory: "14Gi"
      cpu: "4"
    limits:
      memory: "16Gi"
      cpu: "4"

# ====================================================================================================
# Variables for id-editor
# ====================================================================================================
idEditor:
  enabled: true
  image: 'developmentseed/osmseed-id-editor'
  replicaCount: 1
  # Set staticIp, if you are using cloudProvider=gcp
  staticIp: 35.185.241.158
  env:
    OSM_API_PROTOCOL: http
    OSM_API_DOMAIN: 192.168.64.26:32331
    OAUTH_CONSUMER_KEY : xxx
    OAUTH_SECRET : xxx
  resources:
    enabled: false
    requests:
      memory: "300Mi"
      cpu: "0.4"
    limits:
      memory: "400Mi"
      cpu: "0.5"
# ====================================================================================================
# Variables for replication-job, Configuration to create the replication files by, minute, hour, or day
# ====================================================================================================
replicationJob:
  enabled: true
  image: 'developmentseed/osmseed-replication-job'
  resources:
    enabled: false
    requests:
      memory: "20Gi"
      cpu: "8"
    limits:
      memory: "24Gi"
      cpu: "10"

# ====================================================================================================
# Variables for osm-seed to pupulate the apidb
# ====================================================================================================
populateApidb:
  enabled: true
  image: 'developmentseed/osmseed-populate-apidb'
  env:
    URL_FILE_TO_IMPORT: 'http://download.geofabrik.de/europe/monaco-latest.osm.pbf'
  resources:
    enabled: false
    requests:
      memory: "1Gi"
      cpu: "2"
    limits:
      memory: "2Gi"
      cpu: "2.5"

# ====================================================================================================
# Variables to process osm files
# ====================================================================================================
osmProcessor:
  enabled: false
  image: 'developmentseed/osmseed-osm-processor'
  env: 
    URL_FILE_TO_PROCESS: 'https://s3.amazonaws.com/osm-pds/2018/planet-181008.osm.pbf'
    OMS_FILE_ACTION: simple_pbf
  resources:
    enabled: false
    requests:
      memory: "14Gi"
      cpu: "4"
    limits:
      memory: "16Gi"
      cpu: "4"